version: "3.7"

services:
  database:
    image: postgres:9.6
    container_name: "postgres-swl"
    environment:
      - POSTGRES_DB=swl
      - POSTGRES_USER=softwarelab
      - POSTGRES_PASSWORD=softwarelab
      - TZ=UTC
    volumes:
      - "/var/lib/postgresql/data"
    ports:
      - 5436:5432